[package]
name = "assignment7"
version = "0.1.0"
authors = ["telecominventor <jami_ahsan@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
library1 = {path = "../library1"}
